name: weather_app
description: A new Flutter project.
publish_to: none
version: 0.1.0
environment:
    sdk: '>=3.2.3 <4.0.0'
dependencies:
    connectivity_plus: ^2.3.8
    dio: ^5.4.0
    flutter:
        sdk: flutter
    flutter_launcher_icons: ^0.13.1
    geolocator: ^10.1.0
    get: ^4.6.6
    get_storage: ^2.1.1
    # google_fonts: ^6.1.0
    intl: ^0.19.0
flutter_icons:
    android: true
    ios: true
    image_path_android: "assets/icons/Ixon.png"
    image_path_ios: "assets/icons/Ixon.png"


dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.1

flutter:
    uses-material-design: true
    assets:
        - assets/icons/
        - assets/weather/
        - assets/seasons/
    fonts:
      - family: Saira
        fonts:
            - asset: assets/fonts/Saira/Saira-Italic-VariableFont_wdth,wght.ttf
            - asset: assets/fonts/Saira/Saira-VariableFont_wdth,wght.ttf
