name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.6
  intl: ^0.19.0
  location: ^5.0.3
  sleek_circular_slider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/ 
    - assets/imgs/ 

